<?php

class OPCODE
{
        const MIN_SAVING   = 100001;
        const MAX_SAVING   = 100008;
        const MIN_REMOVING = 110001;
        const MAX_REMOVING = 110006;
        const MIN_GETTING  = 120001;
        const MAX_GETTING  = 120009;
        
        const SERVICE_REG_OWNER_REQUEST                = 100001;
	const SERVICE_SAVE_SHOP_REQUEST                = 100002;
	const SERVICE_SAVE_ACCESSPOINT_REQUEST         = 100003;
        const SERVICE_SAVE_PROMOTION_REQUEST           = 100004;
        const SERVICE_SAVE_COPROMOTION_REQUEST         = 100005;
        const SERVICE_SAVE_ACCEPT_COPROMOTION_REQUEST  = 100006;
        const SERVICE_SAVE_COMMENT_REQUEST             = 100007;
        const SERVICE_SAVE_PICTURE_REQUEST             = 100008;
        
        const SERVICE_REMOVE_ACCESSPOINT_REQUEST   = 110001;
	const SERVICE_REMOVE_COMMENT_REQUEST       = 110002;
        const SERVICE_REMOVE_COPROMOTION_REQUEST   = 110003;
        const SERVICE_REMOVE_PROMOTION_REQUEST     = 110004;
        const SERVICE_REMOVE_PICTURE_REQUEST       = 110005;
        const SERVICE_REMOVE_SHOP_REQUEST          = 110006;
        
        const SERVICE_GET_REQUESTED_COPROMOTION_REQUEST  = 120001;
        const SERVICE_GET_COPROMOTION_INFO_REQUEST       = 120002;
        const SERVICE_GET_VALIDATION_LOGIN_REQUEST       = 120003;
        const SERVICE_GET_ACCESSPOINT_REQUEST            = 120004;
        const SERVICE_GET_COMMENT_REQUEST                = 120005;
        const SERVICE_GET_SHOP_INFO_REQUEST              = 120006;
        const SERVICE_GET_SHOP_INFO_REQUEST_BY_BSSID     = 120007;
        const SERVICE_GET_PICTURE_REQUEST                = 120008;
        const SERVICE_GET_PROMOTION_REQUEST              = 120009;
        
	const SERVER_SAVE_SUCCESS_RESPONSE      = 200001;
	const SERVER_SAVE_UNSUCCESS_RESPONSE    = 200002;
	
        const SERVER_REMOVE_SUCCESS_RESPONSE   = 200003;
        const SERVER_REMOVE_UNSUCCESS_RESPONSE = 200004;
        
	const SERVER_ERROR_DUPLICATE_EMAIL_RESPONSE   = 210001;	
	const SERVER_ERROR_DUPLICATE_BSSID_RESPONSE   = 210002;
        const SERVER_ERROR_INVALID_PARAMETER_RESPONSE = 210003;
        
        const SERVER_AUTHENTICATION_INVALID_RESPONSE    = 220001;
        const SERVER_AUTHENTICATION_VALID_RESPONSE      = 220002;
        const SERVER_AUTHENTICATION_INACTIVED_RESPONSE  = 220003;
}

?>
